Repository prisma/graphqlgen, pull requests merged in 2019-01, with the labels that each got.

#306 export enums to allow implementations conforming to them
  packages/graphqlgen/src/generators/common.ts
  packages/graphqlgen/src/tests/flow/__snapshots__/basic.test.ts.snap
  packages/graphqlgen/src/tests/flow/__snapshots__/large-schema.test.ts.snap
  packages/graphqlgen/src/tests/typescript/__snapshots__/basic.test.ts.snap
  packages/graphqlgen/src/tests/typescript/__snapshots__/large-schema.test.ts.snap
Labels: bug/2-confirmed

#353 Check `modelDef.getType()` is defined before use
  packages/graphqlgen/src/generators/common.ts
Labels: bug/0-needs-info

#149 Interface and union resolvers
  packages/graphqlgen/benchmarks/micro/index.ts
  packages/graphqlgen/package.json
  packages/graphqlgen/src/generators/common.spec.ts
  packages/graphqlgen/src/generators/common.ts
  packages/graphqlgen/src/generators/flow-generator.ts
  packages/graphqlgen/src/generators/flow-scaffolder.ts
  packages/graphqlgen/src/generators/ts-generator.ts
  packages/graphqlgen/src/generators/ts-scaffolder.ts
  packages/graphqlgen/src/source-helper.ts
  packages/graphqlgen/src/tests/fixtures/interface/schema.graphql
  packages/graphqlgen/src/tests/fixtures/interface/types.ts
  packages/graphqlgen/src/tests/fixtures/union/schema.graphql
  packages/graphqlgen/src/tests/flow/__snapshots__/basic.test.ts.snap
  packages/graphqlgen/src/tests/typescript/__snapshots__/basic.test.ts.snap
  packages/graphqlgen/src/tests/typescript/basic.test.ts
  packages/graphqlgen/src/types.ts
Labels: kind/feature

#411 feat(gg): simplify and make safer resolver type resovler
  packages/graphqlgen/src/generators/common.ts
  packages/graphqlgen/src/generators/flow-generator.ts
  packages/graphqlgen/src/generators/ts-generator.ts
  packages/graphqlgen/src/source-helper.ts
  packages/graphqlgen/tests/flow/__snapshots__/basic.test.ts.snap
  packages/graphqlgen/tests/typescript/__snapshots__/basic.test.ts.snap
Labels: kind/feature
